name: Deploy

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code using rsync
        run: |
          echo "Starting rsync deployment..."
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude .env --exclude .env.example --exclude .git --exclude .github \
          --exclude vendor --exclude node_modules --exclude tests --exclude storage \
          $GITHUB_WORKSPACE/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/
          echo "Code deployment completed."

      - name: Install dependencies on server
        run: |
          echo "Installing dependencies..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && composer install"
          echo "Dependencies installed."

      - name: Run database migrations
        run: |
          echo "Running database migrations..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && php artisan migrate --force"
          echo "Database migrations completed."

      - name: Optimize Laravel application
        run: |
          echo "Clearing and optimizing application cache..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && php artisan optimize:clear"
          echo "Application optimized."
